project:
  type: website

website:
  title: "Proj-shortcode"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - section: Pages
        contents:
          - about.qmd
          - "{{< meta foo >}}"
          - "{{< meta bar >}}"

metadata-files: 
  - contents.yml
